// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_cognito_identity_pool_id : 'us-east-1:9179b156-ae56-4db5-b27a-790891e771d6',
aws_cognito_region : 'us-east-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'speakeasy-hosting-mobilehub-1041983526',
aws_content_delivery_bucket_region : 'us-east-1',
aws_dynamodb : 'enable',
aws_dynamodb_all_tables_region : 'us-east-1',
aws_dynamodb_table_schemas : '[{"tableName":"expo-mobile-speakeasy","attributes":[{"name":"userId","type":"S"},{"name":"creationDate","type":"N"},{"name":"category","type":"S"},{"name":"completed","type":"B"},{"name":"text","type":"S"},{"name":"todoId","type":"S"}],"indexes":[{"indexName":"DateSorted","hashKey":"userId","rangeKey":"creationDate"}],"region":"us-east-1","hashKey":"userId","rangeKey":"creationDate"}]',
aws_project_id : 'a1dedc66-9522-44ea-829a-7a2fef9cd146',
aws_project_name : 'Speakeasy',
aws_project_region : 'us-east-1',
aws_resource_name_prefix : 'speakeasy-mobilehub-1041983526',
aws_sign_in_enabled : 'enable',
aws_user_files : 'enable',
aws_user_files_s3_bucket : 'speakeasy-userfiles-mobilehub-1041983526',
aws_user_files_s3_bucket_region : 'us-east-1',
aws_user_pools : 'enable',
aws_user_pools_id : 'us-east-1_jcFBITdtb',
aws_user_pools_mfa_type : 'OFF',
aws_user_pools_web_client_id : '6omi5i2c7tb3i0402gd3kn2qm1',
aws_user_settings : 'enable',
}

export default awsmobile;
